dotnet/Microsoft.Maui.Graphics

README.md
#47 makes 2 statements:
1. "premise of the library is based upon a fallacy" - I personally don't believe it's accurate. An efficient UI library needs native-backed graphics.
2. "and harms existing projects" - this is 100% true. This https://github.com/dotnet/Microsoft.Maui.Graphics/issues/47#issuecomment-801068705 explains the problem very well.
This suggestion tries to help with the second point. I believe the community raises very valid concerns which need to be addressed.
=> Suggestion: Do not brand Maui.Graphics as a Microsoft-backed, direct competition to everything graphics-related within the ecosystem

src/Microsoft.Maui.Graphics/Color.cs, tests/Microsoft.Maui.Graphics.Tests/ColorUnitTests.cs
The FromUint implementation has an extra cast to a `double` for the alpha value which corrupts the resulting Color.
Adds a fix for the issue and an automated test.
=> Remove double cast for alpha value from the FromUint method

src/Microsoft.Maui.Graphics/AssemblyInfo.cs, src/Microsoft.Maui.Graphics/XmlnsDefinitionAttribute.cs, src/Microsoft.Maui.Graphics/XmlnsPrefixAttribute.cs
The Visual Studio XAML designers require some attributes for XML namespaces.
=> Add Xmlns attributes for XAML designer

src/Microsoft.Maui.Graphics/LinearGradientPaint.cs, src/Microsoft.Maui.Graphics/RadialGradientPaint.cs, src/Microsoft.Maui.Graphics/SolidPaint.cs
Add more constructors to LinearGradientPaint and RadialGradientPaint. In this way, the initialization of these Paints can be the same as what can be done with brushes in Xamarin.Forms.
=> Added more GradientPaints constructors

src/Microsoft.Maui.Graphics/Color.cs
`ToHex(bool includeAlpha = false)` outputs `#AARRBBGG` which is slightly ambiguous.  Deprecated that method, made the parameter non-optional, and directed to use the new `ToArgbHex()` method instead, and also added a `ToRgbaHex()` method variation.  Finally, added `ToHex()` with no bool parameter which outputs a hex string with no alpha at all.
Similarly, obsoleted the `FromHex` which expects `#AARRBBGG`  as the input, and renamed the parameter name to be more descriptive of the expectation.  `FromHex` just calls `FromArgb(string)` already, so that can be used directly, as well as its already existing `FromRgba(string)` counterpart.
=> Obsolete ambiguous ToHex and FromHex

src/Microsoft.Maui.Graphics/Android/NativeCanvas.cs
All the paints works on Android except the more basic one, the SolidPaint. This PR include changes to fix the issue.
=> Fix issue with SolidPaint in Android

src/Microsoft.Maui.Graphics.GDI.Winforms/GDIImage.cs
`EncoderParameters` was not being disposed which leads to leaking of unmanaged memory. 
As a side note. Contributing this fix was not a great developmental experience. I think it might be wise to add documentation to the readme explaining what VS features are required plus SDK versions in order to successfully build the project.
=> Ensure EncoderParameters is disposed

src/Microsoft.Maui.Graphics.Gtk/Gtk/ColorExtensions.cs
https://developer.gnome.org/gdk3/stable/gdk3-Colors.html#GdkColor
> GdkColor has been deprecated in favor of GdkRGBA.
=> [Gtk] housekeeping: remove Gdk.Color - Conversions

src/Microsoft.Maui.Graphics.Skia/SkiaTextLayout.cs
This PR fix https://github.com/dotnet/Microsoft.Maui.Graphics/issues/106
=> [Skia] Fix DrawString with Vertically center align

.config/dotnet-tools.json, azure-pipelines.yml, build/Build.Microsoft.Maui.Graphics.Mac.sln, build/Build.Microsoft.Maui.Graphics.Windows.sln, build/Microsoft.Maui.Graphics.Skia.nuspec, build/Microsoft.Maui.Graphics.nuspec, src/Microsoft.Maui.Graphics.Skia/Microsoft.Maui.Graphics.Skia-net6.csproj, src/Microsoft.Maui.Graphics.Skia/Microsoft.Maui.Graphics.Skia.csproj, src/Microsoft.Maui.Graphics.Skia/Views/SkiaGraphicsView.Mac.cs, src/Microsoft.Maui.Graphics/Microsoft.Maui.Graphics-net6.csproj, src/Microsoft.Maui.Graphics/Microsoft.Maui.Graphics.csproj
This fix supports `net6.0-tizen`.  
> Make sure that you have to install the Tizen workload for .NET 6.0 (preview) in advance.
> See [here](https://github.com/Samsung/Tizen.NET#installing-tizen-workload-for-net-60-preview).
And, this PR also support `tizen40` for legacy tizen projects.
Thanks to @mattleibow and @Redth for the quick support. ❤️
=> Update Tizen backend

src/Microsoft.Maui.Graphics/Converters/PointFTypeConverter.cs, src/Microsoft.Maui.Graphics/Converters/PointTypeConverter.cs, src/Microsoft.Maui.Graphics/Converters/RectangleFTypeConverter.cs, src/Microsoft.Maui.Graphics/Converters/RectangleTypeConverter.cs, tests/Microsoft.Maui.Graphics.Tests/ColorTypeConverterTests.cs, tests/Microsoft.Maui.Graphics.Tests/PointTypeConverterTests.cs, tests/Microsoft.Maui.Graphics.Tests/RectangleTypeConverterTests.cs, tests/Microsoft.Maui.Graphics.Tests/SizeTypeConverterTests.cs, tests/Microsoft.Maui.Graphics.Tests/TypeConverterExtensions.cs
The type converters are returning false if the string parses to `default`
This means values like "0,0" for point will return false because the default value for point is "0,0" 
This also modifies the unit tests to test against the Type Converters instead of the `TryParse` methods
=> Remove default check on converters

build/Microsoft.Maui.Graphics.Skia.nuspec
Fixes project and repository URLs which currently 404 on the [Microsoft.Maui.Graphics.Skia NuGet page](https://www.nuget.org/packages/Microsoft.Maui.Graphics.Skia). Fixes #137
=> Update Skia package URLs

README.md
Clicking on NuGet image in readme now opens NuGet page on nuget.org.
=> Fix NuGet link

src/Microsoft.Maui.Graphics.GDI.Winforms/GDICanvas.cs, src/Microsoft.Maui.Graphics.GDI.Winforms/GDICanvasState.cs
**This PR improves the WinForms GDI control's support for fills using gradient paints.** It's not perfect (GDI support for gradient fills remains limited), but it's an improvement that may be worth considering. Related #44
_EDIT: When filing rectangles with horizontal or vertical linear gradients (perhaps the most common use case, and fully supported by GDI) the appearance is excellent. It would be great if there were some way to at least support this functionality even if the partial functionality for the rest of the fill types is omitted._
* Based on [this comment block](https://github.com/dotnet/Microsoft.Maui.Graphics/blob/992298f82337726c04ccebc8b464d321f1f66d66/src/Microsoft.Maui.Graphics.GDI.Winforms/GDICanvas.cs#L500-L517) I suspect this was supported in the past. 
* …
=> [WinForms.GDI] improve support for gradient fills

src/Microsoft.Maui.Graphics.Skia.WPF/WDSkiaGraphicsView.cs
This PR fixes a bug that causes the painted area not to match the window when resizing. If the `OnRenderSizeChanged()` override does not call its base implementation the `SizeChanged` event isn't raised and the dirty rectangle may be incorrectly sized when `OnPaintSurface()` is called. Note [mono / SKElement.cs#L88-L93](https://github.com/mono/SkiaSharp/blob/2ad29861d5a40d3bf78c28ab0a9cb02a8f0fe437/source/SkiaSharp.Views/SkiaSharp.Views.WPF/SKElement.cs#L88-L93)
`WDSkiaGraphicsView` inherits `SKElement` which inherits `FrameworkElement`
According to [`FrameworkElement.OnRenderSizeChanged()` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.onrendersizechanged?view=net-5.0): 
> You may still override OnRenderSizeChanged() in derived classes (it is …
=> [Skia.WPF] improve OnRenderSizeChanged()

src/Microsoft.Maui.Graphics/AffineTransform.cs, src/Microsoft.Maui.Graphics/Color.cs, src/Microsoft.Maui.Graphics/Point.cs, src/Microsoft.Maui.Graphics/PointF.cs, src/Microsoft.Maui.Graphics/Size.cs, src/Microsoft.Maui.Graphics/SizeF.cs
Following #136
Added System.Numerics.Vectors constructors and implicit/explicit operator converters to:
- AffineTransform
- Color
- Point
- PointF
- Size
- SizeF
Regarding operators, I followed these rules:
- Vectors to Maui operators are implicit
- Maui to Vectors operators are explicit
- Vectors to Maui (double precission) are implicit
- Maui to Vectors operators (double precission) not implemented to prevent misleading precission loss.
=> Added System.Numerics.Vectors constructors and operators

src/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop/W2DGraphicsView.cs
Because the order of the Loaded/Unloaded events is not guaranteed (see https://github.com/microsoft/microsoft-ui-xaml/issues/1900), removing a W2DGraphicsView from its parent and immediately re-adding it can result in the `UserControl_Unloaded` handler running _after_ the `UserControl_Loaded` handler. This causes the W2DGraphicsView to be removed from the visual tree, and its contents to disappear (https://github.com/dotnet/maui/issues/3214). 
This change adds a check for the CanvasControl's IsLoaded property to verify that the handler is running at a time when the control has actually been unloaded, rather than running out of order. This check can be removed once/if https://github.com/microsoft/microsoft-ui-xaml/issues/1900 is fixed.
=> Verify canvas control is unloaded before removing it

build/Microsoft.Maui.Graphics.Skia.nuspec, src/Microsoft.Maui.Graphics.Skia/Microsoft.Maui.Graphics.Skia-net6.csproj
The update uses a stable WASDK 1.0.0 and also is build with Maui preview 11
=> Bump SkiaSharp to preview 179

src/Microsoft.Maui.Graphics/Point.cs, src/Microsoft.Maui.Graphics/PointF.cs, src/Microsoft.Maui.Graphics/Size.cs, src/Microsoft.Maui.Graphics/SizeF.cs
This PR adds a few operators to make doing calculations with points and sizes easier and more natural.
The biggest addition is the subtration of two points which results in a size. This makes it a lot easier to calculate distances/vectors between two points. This is similar to how subtracting `DateTime` from `DateTime` results in a `TimeSpan`
It also adds operators to divide a size by a scalar. There was already an operator for multiplying by a scalar, but the division operator was missing.
The use case where I ran into these operators missing is when I tried to calculate a point halfway between two points:
`c = a + (b - a) / 2`
`Point - Point -> Size`
`PointF - PointF -> SizeF`
`Size / double -> Size`
`SizeF / float -> SizeF`
=> Point distance

samples/GraphicsTester.Portable/Scenarios/DrawRoundedRectangles.cs, samples/GraphicsTester.Portable/Scenarios/FillRoundedRectangles.cs, src/Microsoft.Maui.Graphics/CanvasExtensions.cs, src/Microsoft.Maui.Graphics/PathF.cs
This PR extends `ICanvas` to support drawing and filling rounded rectangles with user-defined horizontal and vertical corner radii by creating a new `DrawRoundedRectangle()` and `FillRoundedRectangle()` overloads that accept `xRadius` and `yRadius`. Lack of this functionality was noted by @wieslawsoltes in #268.
To simplify review I did not modify the existing [`PathF.AppendRoundedRectangle()`](https://github.com/dotnet/Microsoft.Maui.Graphics/blob/20e0e9e8c78d37575c7c0e1a5c64170616085f0a/src/Microsoft.Maui.Graphics/PathF.cs#L1098-L1125) but these two methods could be collapsed into one. If you want me to do this in PR or make any other changes, let me know.
I also added test patterns to demonstrate this new functionality:
`DrawRoundedRectangle()` | `FillRoundedRectangle()`
---|---
=> Rounded rectangle: add support for distinct X and Y radii

src/Microsoft.Maui.Graphics/Color.cs
This PR adds overloads for the `Color` constructor, `FromRgb()`, and `FromRgba()` that accept `int`.
Reported by @PureWeen in #253 and @davidbritch in #308, there exists a problem where `int` values (expected to be 0-255) are interpreted as `float` and clamped between 0 and 1.0, demonstrated here:
```cs
// fill a circle with a random color using a fluent method
canvas.FillColor = Color.FromRgba(rand.Next(0, 255), rand.Next(0, 255), rand.Next(0, 255), rand.Next(100, 200));
canvas.FillCircle(pt1, radius);
// fill a circle with a random color using a constructor
canvas.FillColor = new Color(rand.Next(0, 255), rand.Next(0, 255), rand.Next(0, 255), rand.Next(100, 200));
canvas.FillCircle(pt2, radius);
```
<details>
<summary>Full source code</summary>
```cs
using Microsoft.Maui.Graphics;
using …
```
=> Color: add overloads so `int` does not get clamped like a `float`

samples/GraphicsTester.Portable/Scenarios/DrawPathsScaled.cs, samples/GraphicsTester.Portable/Scenarios/ScaleCanvas.cs, samples/GraphicsTester.Portable/Scenarios/ScenarioList.cs, src/Microsoft.Maui.Graphics/PathExtensions.cs, src/Microsoft.Maui.Graphics/ScalingCanvas.cs
@mgierlasinski noted in #302 that paths currently can only be scaled evenly by a single number, and that in the `ScaledCanvas` module only the X scale is used. This PR resolves this issue by:
* Adding a `PathF.AsScaledPath()` overload that accepts distinct X and Y scales
* Updating `ScaledCanvas` methods `DrawPath`, `FillPath`, and `ClipPath` to use the new overload
* Adding some graphics test scenarios to demonstrate this behavior
```cs
DrawTestShapesOnScaledCanvas(canvas, 1, 1, Colors.Black);
DrawTestShapesOnScaledCanvas(canvas, 2, 2, Colors.Magenta);
DrawTestShapesOnScaledCanvas(canvas, 2, 1, Colors.Green);
DrawTestShapesOnScaledCanvas(canvas, 1, 2, Colors.Orange);
```
```cs
private void DrawTestShapesOnScaledCanvas(ICanvas canvas, float xScale, float yScale, Color color)
{
PathF path …
```
=> ScalingCanvas: DrawPath, FillPath, and ClipPath respect distinct X and Y scales

azure-pipelines.yml
Follow up fix for https://github.com/dotnet/Microsoft.Maui.Graphics/pull/314
Related work item: VS #[1477663](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1477663)
The signing conditions applied to settings within the SBOM stage are being evaluated too early at the time the YAML file is being "compiled".  We instead need a solution where SBOM configuration settings are applied once the signing condition evaluated at YAML "run time".
Depends on https://github.com/xamarin/yaml-templates/pull/174
=> SBOM: Fix for conditional logic based on signingCondition

src/Microsoft.Maui.Graphics/Color.cs
For hystorical reasons, this code parses colors prefixed with 'Color.'.
This isn't what is expected as a XAML value.
Also, this code removes the fallback for eventually missing colors in
the switch, and fail faster
=> Fix Color Type converter

src/Microsoft.Maui.Graphics/Color.cs, tests/Microsoft.Maui.Graphics.Benchmarks/ColorBenchmarker.cs
The previous change caused a startup-regression with Color because it spends time building up a dictionary as soon as the Color type is touched (in its static ctor). Changing this code back to use pattern-matching, which forces us to allocate a string, for now. Once we have a compiler that supports pattern-matching on a ReadOnlySpan<char>, we can do this allocation free.
This is similar to the original implementation, which also always allocated the lowered string to do pattern matching on.
Here are my benchmark results.
|                             Method |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
|                              Parse | 99.13 ns | …
=> Revert named colors

src/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop-net6.csproj
For fixing CA1416 warnings found in windows build in MAUI repo, like:
```log
This call site is reachable on 'Windows'   10.0.17763.0 and later. 'W2DGraphicsView' is only supported on 'Windows'   10.0.18362.0 and later.
This call site is reachable on 'Windows'   10.0.17763.0 and later. 'W2DGraphicsView.Drawable' is only supported on   'Windows' 10.0.18362.0 and later.
This call site is reachable on 'Windows'   10.0.17763.0 and later. 'W2DGraphicsView.Drawable' is only supported on   'Windows' 10.0.18362.0 and later.
This call site is reachable on 'Windows'   10.0.17763.0 and later. 'W2DGraphicsView.Invalidate()' is only supported on   'Windows' 10.0.18362.0 and later.
This call site is reachable on 'Windows'   10.0.17763.0 and later. 'W2DExtensions.AsPath(PathF, ICanvasResourceCreator, …
```
=> Lower supported version for windows

build/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop.nuspec
As the title says. The Win2D package removes the C++ dependency and that makes our Windows publishing story for .NET MAUI better.
=> Bump WindowsAppSdk and Win2D versions

azure-pipelines.yml
Specifying Tizen sdk version is no longer required. The backup code finding the latest sdk version is embedded in `workload-install.ps1`
=> [Tizen] Remove specifying Tizen sdk version

Directory.Build.props, NuGet.config, azure-pipelines.yml, build.cake, build/DotNet/DotNet.csproj, build/Microsoft.Maui.Graphics.Skia.nuspec, build/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop.nuspec, build/Microsoft.Maui.Graphics.nuspec, eng/Version.Details.xml, eng/Versions.props, eng/cake/dotnet.cake, eng/pipelines/common/provision.yml, eng/provisioning/android.csx, eng/provisioning/provisioning.csx, samples/GraphicsTester.Android/GraphicsTester.Android-net6.csproj, samples/GraphicsTester.Mac/GraphicsTester.Mac-net6.csproj, samples/GraphicsTester.MacCatalyst/GraphicsTester.MacCatalyst-net6.csproj, samples/GraphicsTester.Portable/GraphicsTester.Portable-net6.csproj, samples/GraphicsTester.Skia.Mac/GraphicsTester.Skia.Mac-net6.csproj, samples/GraphicsTester.iOS/GraphicsTester.iOS-net6.csproj, src/Microsoft.Maui.Graphics.Skia/Microsoft.Maui.Graphics.Skia-net6.csproj, src/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop-net6.csproj, src/Microsoft.Maui.Graphics/Microsoft.Maui.Graphics-net6.csproj, tests/Microsoft.Maui.Graphics.Benchmarks/Microsoft.Maui.Graphics.Benchmarks.csproj
We tried triggering subscriptions, such as:
darc trigger-subscriptions --source-repo https://github.com/xamarin/xamarin-android --target-repo https://github.com/dotnet/Microsoft.Maui.Graphics --target-branch net7.0 --verbose
But then no PR opens?
So then I checked the build at:
https://maestro-prod.westus2.cloudapp.azure.com/2237/https:%2F%2Fgithub.com%2Fxamarin%2Fxamarin-android/latest/graph
Using the build id:
darc update-dependencies --id 136370 --verbose
We get the error:
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
Non-continuable HTTP 401 error encountered while making request
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at …
=> [maestro] manually adjusting versions for .NET 7

README.md
Today I noticed _implementations_ is spelled incorrectly in the opening paragraph 😅
Congratulations on getting out of preview!
=> Fix spelling in main readme

src/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop/PlatformImage.cs, src/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop/W2DCanvas.cs, src/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop/W2DImageLoadingService.cs
With this changes we can avoid this issue:
@jonlipsky Why was the W2DImage an internal class?
Fixes #457
Fixes #402
=> Rename W2DImage to PlatformImage

NuGet.config, build/Microsoft.Maui.Graphics.Skia.nuspec, build/Microsoft.Maui.Graphics.nuspec, eng/Versions.props, samples/GraphicsTester.Skia.Console/GraphicsTester.Skia.Console.csproj, samples/GraphicsTester.Skia.Mac/GraphicsTester.Skia.Mac-net6.csproj, samples/GraphicsTester.Skia.Mac/GraphicsTester.Skia.Mac.csproj, samples/GraphicsTester.Skia.Windows/GraphicsTester.Skia.Windows.csproj, src/Microsoft.Maui.Graphics.Skia.GtkSharp/Microsoft.Maui.Graphics.Skia.GtkSharp.csproj, src/Microsoft.Maui.Graphics.Skia.WPF/Microsoft.Maui.Graphics.Skia.WPF.csproj, src/Microsoft.Maui.Graphics.Skia/Microsoft.Maui.Graphics.Skia-net6.csproj, src/Microsoft.Maui.Graphics.Skia/Microsoft.Maui.Graphics.Skia.csproj, src/Microsoft.Maui.Graphics.Skia/PublicAPI/net-tizen/PublicAPI.Shipped.txt, src/Microsoft.Maui.Graphics.Skia/Views/SkiaGraphicsView.Tizen.nui.cs, src/Microsoft.Maui.Graphics/Microsoft.Maui.Graphics-net6.csproj, src/targets/MultiTargeting.targets
This PR is to change the tizen backend implementation of SkiaGrpahicsView from EFL (legacy Tizen UI FW) to NUI (brand new Tizen .NET UI FW). Please refer to MAUI([#9620](https://github.com/dotnet/maui/pull/9620)) and SkiaSharp([#2225](https://github.com/mono/SkiaSharp/pull/2225)) fixes related to this together.
~> Keep this PR as a draft until a new version of SkiaSharp packages is released.~
=> [Tizen] Add NUI-based SkiaGraphicsView for net6
